### ISSUE TITLE
Gizmo is drawn at a scale

### ISSUE THREAD

**Issue by schroef** [pKrime/PizMo#4]
v0.2.2
osx 10.11.6
bl 2.83

Was doing a super simple test with Suzanne head, was reading about the Bone-Widget addon and remembered the earlier
 Face Map concept i saw 2-3 years back orso. Tried using this addon and it does work, yet i see the gizmos being drawn in a small scale. 

As more info lacks, im not sure if this proper behavior

Attached screengrab and test file
![Screen Shot 2021-11-09 at 17 40 14](https://user-images.githubusercontent.com/6923008/141009773-368884ad-6a0b-4c06-9f6b-394e25099c55.png)
![Screen Shot 2021-11-09 at 17 40 04](https://user-images.githubusercontent.com/6923008/141009779-6dabee28-7587-4467-a085-dc2ebba2d5be.png)
[Gone-Gizmo.blend.zip](https://github.com/pKrime/PizMo/files/7508172/Gone-Gizmo.blend.zip)

**Comment by schroef** [comment]
Just noticed when i move or scale it seems to have a different offset. Moving 3dv also has some awkward results
![different 3dv scale](https://user-images.githubusercontent.com/6923008/141010286-cc158620-5051-4efc-a1e5-4e970d8cb8a4.gif)

**Comment by pKrime** [comment]
Hi, your file looks great when I open it, but I can reproduce the issue if I scale Suzanne. I hadn't looked into the object transforms yet, but I have pushed a quick fix. Can you please download and check version 0.2.3?

Cheers

**Comment by schroef** [comment]
Ill try again. I later noticed i also used a scale in the global settings of the Gizmo

**Comment by schroef** [comment]
Im not actually scaling the object, the object isnt scaled neither. Im zooming in and out in the 3dview
Its not fixed, it does look your almost here, it looks like it contra in scale by just a bit

I attached a test scene in the first post, you can see it very clear in this case

![differenent 3dv scale-v023-v2](https://user-images.githubusercontent.com/6923008/142071849-0470f52c-e06b-4623-86dc-7a700490219b.gif)
![differenent 3dv scale-v023](https://user-images.githubusercontent.com/6923008/142071868-d3ff45fc-4d8a-47c7-b971-e3e6b9d9e5fe.gif)
